// ===========================================================================
//  slice-sheets.mjs — cuts Tuxemon battle sheets into game-ready sprites.
//
//  Run it from the tools/ folder (never in the browser):
//      cd tools && npm install && npm run slice
//
//  INPUT:  ../assets/sprites/battle/<slug>-sheet.png   (vendored sheets)
//          sheet-manifest.json                          (attribution per slug)
//  OUTPUT: ../assets/sprites/front/<slug>.png   64×64  front pose
//          ../assets/sprites/back/<slug>.png    64×64  back pose
//          ../assets/sprites/idle/<slug>.png    48×24  two 24×24 idle frames,
//                                               side by side — the little
//                                               sprite that stands on the map
//          credits-fragment.md                  a CREDITS.md table fragment,
//                                               generated so attribution rows
//                                               never have to be hand-typed
//
//  SHEET LAYOUT (measured 2026-07-06 against 10 real sheets — note this is
//  NOT the "2×2 grid of 64×44 cells" some older docs described):
//
//        ┌───────────────┬───────────────┐
//        │  front pose   │   back pose   │   each 64×64
//        │   (0,0)       │   (64,0)      │
//        ├───────┬───────┼───────────────┘
//        │ idle 1│ idle 2│                   each 24×24, at (0,64) and (24,64)
//        └───────┴───────┘
//
//  A sheet with no manifest entry is SKIPPED with a warning — no asset
//  ships without attribution (CONTENT_REFERENCE.md §14). Add the entry
//  (checking the artist/license first!), then re-run.
// ===========================================================================

import sharp from "sharp";
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const TOOLS = dirname(fileURLToPath(import.meta.url));
const SHEETS = join(TOOLS, "..", "assets", "sprites", "battle");
const OUT = join(TOOLS, "..", "assets", "sprites");

// Where each piece lives on the sheet (left, top, width, height).
const CELLS = {
  front: { left: 0, top: 0, width: 64, height: 64 },
  back: { left: 64, top: 0, width: 64, height: 64 },
  idle: { left: 0, top: 64, width: 48, height: 24 }, // both frames, as one strip
};

const manifest = JSON.parse(readFileSync(join(TOOLS, "sheet-manifest.json"), "utf8"));

const sheets = readdirSync(SHEETS).filter((f) => f.endsWith("-sheet.png"));
const creditRows = [];
let sliced = 0;
let skipped = 0;

for (const file of sheets) {
  const slug = file.replace("-sheet.png", "");
  const entry = manifest[slug];

  if (!entry) {
    console.warn(`⚠️  SKIPPED ${file} — no entry in sheet-manifest.json (attribution required)`);
    skipped++;
    continue;
  }

  const src = join(SHEETS, file);
  for (const [kind, cell] of Object.entries(CELLS)) {
    mkdirSync(join(OUT, kind), { recursive: true });
    await sharp(src).extract(cell).toFile(join(OUT, kind, `${slug}.png`));
  }

  creditRows.push(
    `| ${entry.ourName} (front/back/idle sprites) | \`assets/sprites/{front,back,idle}/${slug}.png\` | ` +
      `\`mods/tuxemon/gfx/sprites/battle/${slug}-sheet.png\` | ${slug} | ${entry.artists} | ${entry.license} |`
  );
  console.log(`✂️  ${slug} → front/back/idle (for ${entry.ourName})`);
  sliced++;
}

const fragment = [
  "<!-- Generated by tools/slice-sheets.mjs — paste new rows into CREDITS.md's",
  '     "In use" table when a creature\'s sliced sprites enter the game. -->',
  "",
  "| Our name | File in our repo | Source in Tuxemon repo | Tuxemon name | Artist(s) | License |",
  "|---|---|---|---|---|---|",
  ...creditRows,
  "",
].join("\n");
writeFileSync(join(TOOLS, "credits-fragment.md"), fragment);

console.log(`\nDone: ${sliced} sheet(s) sliced, ${skipped} skipped.`);
console.log("Attribution rows written to tools/credits-fragment.md");
